backend:
  name: git-gateway
  branch: main

media_folder: 'assets/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'index.html'
        fields:
          - { label: 'Hero Title', name: 'hero_title', widget: 'string' }
          - {
              label: 'Hero Description',
              name: 'hero_description',
              widget: 'text',
            }
          - { label: 'Hero Image', name: 'hero_image', widget: 'image' }
          - label: 'Features'
            name: 'features'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Icon', name: 'icon', widget: 'image' }

      - label: 'Team'
        name: 'team'
        file: 'team.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - label: 'Team Members'
            name: 'team_members'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Position', name: 'position', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Bio', name: 'bio', widget: 'text' }

      - label: 'FAQ'
        name: 'faq'
        file: 'faq.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'FAQ Items'
            name: 'faq_items'
            widget: 'list'
            fields:
              - { label: 'Question', name: 'question', widget: 'string' }
              - { label: 'Answer', name: 'answer', widget: 'text' }

      - label: 'Contact'
        name: 'contact'
        file: 'contact-us.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Contact Email', name: 'email', widget: 'string' }
          - { label: 'Contact Phone', name: 'phone', widget: 'string' }
          - { label: 'Address', name: 'address', widget: 'text' }

  - name: 'blog'
    label: 'Blog Posts'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'portfolio'
    label: 'Portfolio'
    folder: '_portfolio'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  - name: 'careers'
    label: 'Career Opportunities'
    folder: '_careers'
    create: true
    fields:
      - { label: 'Position Title', name: 'title', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Department', name: 'department', widget: 'string' }
      - {
          label: 'Type',
          name: 'type',
          widget: 'select',
          options: ['Full-time', 'Part-time', 'Contract'],
        }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Requirements', name: 'requirements', widget: 'markdown' }
